### ISSUE TITLE
Error en los colores del dialogo y error al abrir

### ISSUE THREAD

**Issue by jordyamc** [munix/Multi-Display-Cast#1]
Mi app tiene la opción de poner en modo obscuro, pero el dialogo de seleccion de dispositivos ignora los colores de mi tema y muestra el fondo blanco

y de vez en cuando me marca este error:

```
Attempt to invoke virtual method 'java.util.List com.connectsdk.service.DeviceService.getCapabilities()' on a null object reference
          java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.connectsdk.service.DeviceService.getCapabilities()' on a null object reference
          at com.connectsdk.device.ConnectableDevice.addService(ConnectableDevice.java:181)
          at com.connectsdk.device.ConnectableDevice.<init>(ConnectableDevice.java:136)
          at com.connectsdk.device.DefaultConnectableDeviceStore.getDevice(DefaultConnectableDeviceStore.java:232)
          at com.connectsdk.discovery.DiscoveryManager.onServiceAdded(DiscoveryManager.java:701)
          at com.connectsdk.discovery.provider.SSDPDiscoveryProvider$6.run(SSDPDiscoveryProvider.java:439)

```

**Comment by munix** [comment]
@jordyamc el crash lo estoy revisando. Lo del tema oscuro tendrás que darle un retoque a los styles de la librería para usar el tema básico que necesites en tu app

**Comment by jordyamc** [comment]
También podrías poner en CastManager.getInstance().setDiscoveryManager(); una forma de agregar filtros y así poder soportar los dispositivos según la funcionalidad de la app

**Comment by munix** [comment]
Se aceptan pull requests
